export const movesData = [
    'Accelerate', 'Aim', 'Bait', 'Barter', 'Battle Chime', 'Battle Horn', 'Bequeath',
    'Body Slam', 'Brace', 'Chase Down', 'Climate Cannon', 'Conclusion', 'Dawdle', 'Daydream',
    'Dissonant Chord', 'Dodge', 'Drudge', 'Ear Slap', 'Eerie Stare', 'Enamor', 'Examine', 
    'Give Up', 'Gnaw', 'Growl', 'Harmonious Chord', 'Headbutt', 'High-Pitch Screech',
    'Ill Will', 'Nab', 'Pounce', 'Power Focus', 'Quick Pounce', 'Raging Howl', 'Raging Tackle',
    'Rainbow Blast', 'Recycle', 'Rejuvenate', 'Repeating Tune', 'Resonate', 'Scapegoat',
    'Shriek', 'Slash', 'Slumber', 'Spare', 'Spit', 'Spit Out', 'Squawk', 'Stampede', 'Stare',
    'Stretch', 'Strike', 'Summon', 'Swipe', 'Tail Slap', 'Teamwork', 'Tear Down', 'Tone Barrier',
    'Tribute', 'Blaze Chomp', 'Blaze Punch', 'Boiling Press', 'Burn Up', 'Eruption', 'Fiery Fondant',
    'Fire Breath', 'Fire Slam', 'Flaming Kick', 'Flare Blast', 'Heat Wave', 'Hellstorm', 
    'Kindled Rage', 'Lava Slash', 'Magma Block', 'Magma Burst', 'Pepper Burst', 'Phoenix Flame',
    'Pyrokinesis', 'Raging Flame', 'Rapid Fire', 'Singe', 'Aqua Jaws', 'Douse', 'Downpour', 
    'Geyser', 'Headless Rush', 'Hydro Blast', 'Hydro Slash', 'Maroon', 'Marsh Wave', 'Piercing Drive',
    'Plunge', 'Shell Bash', 'Shell Shrapnel', 'Soft Water', 'Spray', 'Submerge', 'Torrential Slash',
    'Tsunami', 'Vicious Snap', 'Water Bomb', 'Wave Wrecker', 'Briar Block', 'Bush Whack', 
    'Carnivorous Snap', 'Coconut Bomb', 'Flora Blast', 'Fungus Curse', 'Harvest', 'Leaf Barrage',
    'Life Drain', 'Nature\'s Force', 'Nature\'s Rage', 'Petal Pummel', 'Photosynthesis', 
    'Pine Shot', 'Sap Plant', 'Snore Spores', 'Static Spores', 'Take Root', 'Thistle Slash',
    'Thorn Slam', 'Timber Thrash', 'Trip root', 'Wonder Herb', 'Blindspot Batter', 'Dazzling Barrage',
    'Disperse', 'Energy Surge', 'Flare', 'Flash', 'Flash \'n Flee', 'Flash Pulse', 'Gamma Pulse',
    'Hyper String', 'Light Dash', 'Lightspeed Ray', 'Luminous Roar', 'Luster Loot', 'Magnify',
    'Nova Blast', 'Radiant Forecast', 'Radiant Rush', 'Shine', 'Solar Punch', 'Baffle',
    'Bag of Tricks', 'Bamboozle', 'Blood Drain', 'Charade', 'Chomp', 'Dark Surge', 'Dive Bomb',
    'Egg Lob', 'Egg Storm', 'Gain Drain', 'Gloom Fangs', 'Gnarly Gash', 'Mega Chomp', 'Pilfer',
    'Provoke', 'Rant', 'Revolution', 'Shadow Lurk', 'Shadow Pulse', 'Sharpen', 'Sinister Shackles',
    'Slap Down', 'Soul Drain', 'Spite', 'Square One', 'Talent Trade', 'Tricky Tactics', 'Tease',
    'Brain Freeze', 'Chilly Chomp', 'Deep Freeze', 'Flurry', 'Frost Beam', 'Frost Breath',
    'Frost Punch', 'Ice Hammer', 'Icicle Trap', 'Icicle Tremor', 'Out of Order', 'Peppermint Breath',
    'Sleet Shot', 'Snot Shot', 'Snowdozer', 'Winter\'s Fury', 'Electro Blast', 'Electro-Punch',
    'Electroburst', 'Energize', 'Fulgur Fangs', 'Jolt', 'Jump Start', 'Power Draw', 'Power Siphon',
    'Power Surge', 'Precision Bolt', 'Static Shock', 'Storm Summon', 'Tase', 'Thunder Blast',
    'Thunder Chomp', 'Thunder Clap', 'Thunder Crash', 'Thunder Slam', 'Thunderstorm',
    'Thunderstrike', 'Zip-Zap', 'Air Blade', 'Air Shot', 'Air Whipe', 'Cyclone Slam', 'Double Beat',
    'Gale Force', 'Gust', 'Jet Stream', 'Nosedive', 'Peck', 'Perch', 'Ruffled Feathers',
    'Scavenge', 'Second Wind', 'Tempest', 'Typhoon', 'Wing Slap', 'Battering Ram', 'Bug Bite',
    'Clamp Claw', 'Discordance', 'Double Sting', 'Molt', 'Mystic Breeze', 'Parasitize',
    'Pester', 'Pestilence', 'Pheroblast', 'Twirly Whirl', 'Web Shot', 'Boulder Blast', 'Burrow',
    'Clay Slap', 'Earthquake', 'Landslide', 'Muck Buck', "Mud Spatter", "Mudslide", "Quicksand", 
    "Tamp", "Yeti's Wrath", "Baneful Bash", "Barb Trap", "Canister Burst", "Corrode", "Gobble Goop",
    "Graffiti", "Muck Blast", "Oil Leak", "Paint Shower", "Poison",
    "Poison Barbs", "Slime", "Sting", "Toxiblast", "Toxic Spores",
    "Toxic Tail", "Venom Chomp", "Venom Slash", "Airstrike", "Armor Down",
    "Barbs", "Bash", "Clamp", "Complete Demolition", "Dart Burst",
    "Double Whack", "Heavy Bash", "Holy Slash", "Metal Blast", "Metal Shriek",
    "Metal Swipes", "Razor Slash", "Reflection Burst", "Searing Steel", "Steel Crusher",
    "Steel Trap", "Tune-up", "Vice Jaws", "Ancient Roar", "Augment",
    "Bane of Haste", "Beast's Slumber", "Confound", "Dino Claws", "Draco Beam",
    "Elemental Burst", "Energy Break", "Far Enchantment", "Goop Spout", "Meteor Crash",
    "Meteor Smash", "Near Enchantment", "Outburst", "Primal Slash", "Savage Greed",
    "Shrewd Blast", "Apparition", "Emulate", "Fade Away", "Final Ruse",
    "Frightful Surprise", "Ghostly Howl", "Harrow", "Hazy Shroud", "Impersonate",
    "Oppress", "Phantom Blast", "Phantom Slash", "Revival", "Shadow Sprint",
    "Shatter", "Soul Harvest", "Soul Storm", "Spectral Burst", "Startle",
    "Stupefy", "Bludgeon", "Body Crash", "Boom Bash", "Brawn Boost",
    "Buck Up", "Bulk Up", "Chop", "Clawber", "Counter Stance",
    "Driving Force", "Heart Break", "Hop Kick", "Horn-Dashi", "Junglejutsu",
    "Mega Kick", "Mega Punch", "Pep Jab", "Preemptive Strike", "Punch",
    "Quick Punch", "Rogue Assault", "Rough Up", "Shadowbox", "Swat",
    "Vital Jab", "Brain Exercise", "Brainwash", "Cerebral Slash", "Déjà Vu", "Deja Vu",
    "Dissipate", "Empathize", "Energy Gift", "Flabbergast", "Foul Chant",
    "Health Gift", "Hypnotize", "Memorize", "Mind's Eye", "Peace of Mind",
    "Psychal Slap", "Psycho Blast", "Return to Sender", "Splitting Headache", "Stratagem",
    "Telekinetic Sweep", "Adaptive Assault", "Expert Onslaught", "Gloominous Roar" 
]; 

export default movesData;